spring:
  application:
    name: Eureka-server

server:
  port: 1111

eureka:
  instance:
    hostname: server1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka2.com:1111/eureka/,http://eureka3.com:1113/eureka/