spring:
  application:
    name: Eureka-server

server:
  port: 1113

eureka:
  instance:
    hostname: server3
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka1.com:1111/eureka/,http://eureka2.com:1113/eureka/