spring:
  application:
    name: Eureka-server

server:
  port: 1112

eureka:
  instance:
    hostname: server2
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://serve1:1111/eureka/