spring:
  application:
    name: Eureka-server

server:
  port: 1112

eureka:
  instance:
    hostname: server2 #eureka 服务端的实例名称
    prefer-ip-address: true
  client:
    registerWithEureka: false #表示向eureka注册中心注册自己
    fetchRegistry: false      #false，则表示自己为注册中心
    service-url:              #监控页面
      defaultZone: http://eureka1.com:1111/eureka/,http://eureka3.com:1113/eureka/